const useLeftSideNavigation = () => {
  const list = [
    {
      defaultDisplay: true,
      icon: 'https://scontent-tpe1-1.xx.fbcdn.net/v/t1.6435-1/cp0/p40x40/82855035_2877650045589789_7997259028189151232_n.jpg?_nc_cat=104&ccb=1-3&_nc_sid=dbb9e7&_nc_ohc=FaTt1BIUDc4AX8DUnv1&_nc_oc=AQlw6goNkkey7FdAo-Qs8yUEIvK4SYPfkpfrYD7GQV85k-hAXGY8UE17OLn83pwdMTA&_nc_ht=scontent-tpe1-1.xx&tp=27&oh=464bcee60f49055df1adcd3ecdb4918d&oe=60E18873',
      title: 'User',
      notification: 0,
      pathname: '',
    },
    {
      defaultDisplay: true,
      icon: 'https://static.xx.fbcdn.net/rsrc.php/v3/yx/r/5rR6LRpNc5u.png',
      title: 'COVID-19 Information Center',
      notification: 0,
      pathname: '',
    },
    {
      defaultDisplay: true,
      icon: 'https://static.xx.fbcdn.net/rsrc.php/v3/y8/r/S0U5ECzYUSu.png',
      title: 'Friends',
      notification: 0,
      pathname: '',
    },
    {
      defaultDisplay: true,
      icon: 'https://static.xx.fbcdn.net/rsrc.php/v3/yH/r/kyCAf2jbZvF.png',
      title: 'Pages',
      notification: 9,
      pathname: '',
    },
    {
      defaultDisplay: true,
      icon: 'https://static.xx.fbcdn.net/rsrc.php/v3/y5/r/PrjLkDYpYbH.png',
      title: 'Groups',
      notification: 0,
      pathname: '',
    },
    {
      defaultDisplay: true,
      icon: 'https://static.xx.fbcdn.net/rsrc.php/v3/yU/r/D2y-jJ2C_hO.png',
      title: 'Marketplace',
      notification: 0,
      pathname: '',
    },
    {
      defaultDisplay: false,
      icon: 'https://static.xx.fbcdn.net/rsrc.php/v3/yD/r/CwKNCefmHON.png',
      title: 'Ad Center',
      notification: 0,
      pathname: '',
    },
    {
      defaultDisplay: false,
      icon: 'https://static.xx.fbcdn.net/rsrc.php/v3/y9/r/DHBHg9MEeSC.png',
      title: 'Ads Manager',
      notification: 0,
      pathname: '',
    },
    {
      defaultDisplay: false,
      icon: 'https://static.xx.fbcdn.net/rsrc.php/v3/y8/r/p1ZJABzCAAS.png',
      title: 'Blood Donations',
      notification: 0,
      pathname: '',
    },
    {
      defaultDisplay: false,
      icon: 'https://static.xx.fbcdn.net/rsrc.php/v3/y8/r/29AMNpNZ4Vm.png',
      title: 'Campus',
      notification: 0,
      pathname: '',
    },
    {
      defaultDisplay: false,
      icon: 'https://static.xx.fbcdn.net/rsrc.php/v3/y3/r/Jr0q8qKF2-Y.png',
      title: 'Climate Science Information',
      notification: 0,
      pathname: '',
    },
    {
      defaultDisplay: false,
      icon: 'https://static.xx.fbcdn.net/rsrc.php/v3/yT/r/cT5nPnO8Wsc.png',
      title: 'Crisis Response',
      notification: 0,
      pathname: '',
    },
    {
      defaultDisplay: false,
      icon: 'https://static.xx.fbcdn.net/rsrc.php/v3/y5/r/vxMUnHhu6Do.png',
      title: 'Emotional Health',
      notification: 0,
      pathname: '',
    },
    {
      defaultDisplay: false,
      icon: 'https://static.xx.fbcdn.net/rsrc.php/v3/ys/r/8wTx0Eu2vRq.png',
      title: 'Events',
      notification: 0,
      pathname: '',
    },
    {
      defaultDisplay: false,
      icon: 'https://static.xx.fbcdn.net/rsrc.php/v3/yv/r/GJ4EaivDaSj.png',
      title: 'Facebook Pay',
      notification: 0,
      pathname: '',
    },
    {
      defaultDisplay: false,
      icon: 'https://static.xx.fbcdn.net/rsrc.php/v3/yK/r/mAnT0r8GSOm.png',
      title: 'Favorites',
      notification: 0,
      pathname: '',
    },
    {
      defaultDisplay: false,
      icon: 'https://static.xx.fbcdn.net/rsrc.php/v3/yQ/r/MN5ZSGIfEZ3.png',
      title: 'Friend Lists',
      notification: 0,
      pathname: '',
    },
    {
      defaultDisplay: false,
      icon: 'https://static.xx.fbcdn.net/rsrc.php/v3/yj/r/n2vd2VduYc1.png',
      title: 'Fundraisers',
      notification: 0,
      pathname: '',
    },
    {
      defaultDisplay: false,
      icon: 'https://static.xx.fbcdn.net/rsrc.php/v3/yy/r/9bekmF_PzNp.png',
      title: 'Gaming Video',
      notification: 4,
      pathname: '',
    },
    {
      defaultDisplay: false,
      icon: 'https://static.xx.fbcdn.net/rsrc.php/v3/yo/r/DO-SN-shaZL.png',
      title: 'Jobs',
      notification: 0,
      pathname: '',
    },
    {
      defaultDisplay: false,
      icon: 'https://static.xx.fbcdn.net/rsrc.php/v3/yG/r/Nl9CPY6q_n-.png',
      title: 'Live Videos',
      notification: 0,
      pathname: '',
    },
    {
      defaultDisplay: false,
      icon: 'https://static.xx.fbcdn.net/rsrc.php/v3/y8/r/he-BkogidIc.png',
      title: 'Memories',
      notification: 0,
      pathname: '',
    },
    {
      defaultDisplay: false,
      icon: 'https://static.xx.fbcdn.net/rsrc.php/v3/y5/r/4Y9Xi2D3hJv.png',
      title: 'Messenger',
      notification: 0,
      pathname: '',
    },
    {
      defaultDisplay: false,
      icon: 'https://static.xx.fbcdn.net/rsrc.php/v3/yu/r/1Xvrz50fHMF.png',
      title: 'Messenger Kids',
      notification: 0,
      pathname: '',
    },
    {
      defaultDisplay: false,
      icon: 'https://static.xx.fbcdn.net/rsrc.php/v3/ye/r/w-vdKCGzCy1.png',
      title: 'Most Recent',
      notification: 0,
      pathname: '',
    },
  ];

  return { list };
};

export default useLeftSideNavigation;
